apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: sav-frontend
build:
  artifacts:
    - image: us.gcr.io/p-savvy/sav-frontend
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
