const PeopleActionTypes = {
  FETCH_PEOPLE_START: "FETCH_PEOPLE_START",
  FETCH_PEOPLE_SUCCESS: "FETCH_PEOPLE_SUCCESS",
  FETCH_PEOPLE_ERROR: "FETCH_PEOPLE_ERROR",
  SET_PEOPLE_FILTER: "SET_PEOPLE_FILTER",
  TOGGLE_INVITE_PEOPLE: "TOGGLE_INVITE_PEOPLE",
  RESET_PEOPLE: "RESET_PEOPLE",
};

export default PeopleActionTypes;
