const BoardsActionTypes = {
  FETCH_BOARDS_START: "FETCH_BOARDS_START",
  FETCH_BOARDS_SUCCESS: "FETCH_BOARDS_SUCCESS",
  FETCH_BOARDS_ERROR: "FETCH_BOARDS_ERROR",
  SET_BOARDS_FILTER: "SET_BOARDS_FILTER",
  TOGGLE_EDIT_BOARD: "TOGGLE_EDIT_BOARD",
  FETCH_BOARD_START: "FETCH_BOARD_START",
  FETCH_BOARD_SUCCESS: "FETCH_BOARD_SUCCESS",
  FETCH_BOARD_ERROR: "FETCH_BOARD_ERROR",
  EDIT_BOARD_START: "EDIT_BOARD_START",
  EDIT_BOARD_SUCCESS: "EDIT_BOARD_SUCCESS",
  EDIT_BOARD_ERROR: "EDIT_BOARD_ERROR",
};

export default BoardsActionTypes;
