const CanvasActionTypes = {
  FETCH_CARDS_START: "FETCH_CARDS_START",
  FETCH_CARDS_SUCCESS: "FETCH_CARDS_SUCCESS",
  FETCH_CARDS_ERROR: "FETCH_CARDS_ERROR",
  UPDATE_CACHED_CARD_TEXT: "UPDATE_CARD",
  SUBSCRIBE: "SUBSCRIBE",
  UNSUBSCRIBE: "UNSUBSCRIBE",
};

export default CanvasActionTypes;
