name: cd
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          bump-minor-pre-major: true
          pull-request-title-pattern: 'chore: release ${version}'
  
  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: authenticate
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: setup gcloud
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: configure gcloud docker
      run: gcloud auth configure-docker

    - name: build image
      run: docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ needs.release.outputs.tag_name }} . 
      
    - name: push to gcr
      run:  docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ needs.release.outputs.tag_name }}

  deploy:
    needs: [release, publish]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: authenticate
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: get gke credentials 
      id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: '${{ secrets.GCP_CLUSTER_NAME }}'
        location: '${{ secrets.GCP_CLUSTER_REGION }}'

    - name: apply k8s files
      run: 'kubectl apply -f k8s'

    - name: update deployment image
      run: 'kubectl set image deployments/${{ github.event.repository.name }} ${{ github.event.repository.name }}=us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ needs.release.outputs.tag_name }}'
